

services:
  condimentos-app-test:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - user=laravel
        - uid=1000
    image: condimentos-app
    container_name: condimentos-app-test
    restart: unless-stopped
    networks:
      - condimentos-network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: condimentos-nginx
    ports:
      - "6162:80"
    networks:
      - condimentos-network


networks:
  condimentos-network:
    driver: bridge