
# Used for prod build.
FROM php:8.4-fpm as php

ARG user
ARG uid

# Set environment variables
ENV PHP_OPCACHE_ENABLE=1
ENV PHP_OPCACHE_ENABLE_CLI=0
ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
ENV PHP_OPCACHE_REVALIDATE_FREQ=0

# Install dependencies.
#* RUN apt-get update && apt-get install -y unzip libpq-dev libcurl4-gnutls-dev nginx libonig-dev
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions.
#* RUN docker-php-ext-install mysqli pdo pdo_mysql bcmath curl opcache mbstring
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Copy composer executable.
COPY --from=composer:2.6.6 /usr/bin/composer /usr/bin/composer
#! COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN useradd -u $uid -ms /bin/bash -g www-data $user


# Copy configuration files.
#* COPY ./docker-performance/php/php.ini /usr/local/etc/php/php.ini
COPY ./docker-performance/php/local.ini /usr/local/etc/php/conf.d/local.ini

COPY ./docker-performance/php/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf
# COPY ./docker-performance/nginx/nginx.conf /etc/nginx/nginx.conf

# Set working directory to /var/www.
WORKDIR /var/www/html

# Copy files from current folder to container current folder (set in workdir).
#* COPY --chown=www-data:www-data . .
COPY . /var/www/html
COPY --chown=$user:www-data . /var/www/html


# Create laravel caching folders.
RUN mkdir -p /var/www/html/storage/framework
RUN mkdir -p /var/www/html/storage/framework/cache
RUN mkdir -p /var/www/html/storage/framework/testing
RUN mkdir -p /var/www/html/storage/framework/sessions
RUN mkdir -p /var/www/html/storage/framework/views

# Fix files ownership.
RUN chown -R $user:www-data /var/www/html/storage
RUN chown -R $user:www-data /var/www/html/storage/framework
RUN chown -R $user:www-data /var/www/html/storage/framework/sessions

# Set correct permission.
RUN chmod -R 775 /var/www/html/storage
RUN chmod -R 775 /var/www/html/storage/logs
RUN chmod -R 775 /var/www/html/storage/framework
RUN chmod -R 775 /var/www/html/storage/framework/sessions

USER $user

EXPOSE 9000

# Run the entrypoint file.
ENTRYPOINT [ "docker-performance/php/entrypoint.sh" ]